### ISSUE TITLE
install Newslynx

### ISSUE THREAD

**Issue by medikiaei** [newslynx/user-manual#1]
Hi ,

I use Windows-Server and want to run **Newslynx** on my Server to Analyse my Website. I can't understand what should I do and how to configure it. what do I need to run **Newslynx** on my Server?

Best Regards
Medi Kiaei

**Comment by mhkeller** [comment]
Hi @medikiaei, We never tested it on Windows so I wouldn't expect it to work on that platform. We used Ubuntu AWS servers but since it has been a few years since we have worked on this project, I'm not sure how successful it will be to get it working.

**Comment by medikiaei** [comment]
Hi @mhkeller , Thanks for your response. I've seen that Newslynx has Mac version too. Can we use this version to Analyse our Websites?

**Comment by mhkeller** [comment]
That desktop version is a replacement for the front-end and web server but it would still rely on an API server. I wouldn't expect this to still be working.
